name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # clang on macos-latest cannot compile ranges
        os: [ubuntu-latest]
        compiler: [g++-13]
        exclude:
          # Only default compiler on ubuntu-latest
          - os: ubuntu-latest
            compiler: clang
        include:
          - os: ubuntu-latest
            compiler: g++-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build binaries
      run: make release_debug

    - name: Build tests
      run: make release_debug_test

    - name: Run tests
      run: make run_release_debug_test
