name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            compiler: [g++-13,clang++-16]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install compiler
      run: sudo apt install g++-13 clang-16

    - name: Build binaries
      env:
          CXX: ${{ matrix.compiler }}
      run: make -j5 release_debug

    - name: Build tests
      env:
          CXX: ${{ matrix.compiler }}
      run: make -j5 release_debug_test

    - name: Run tests
      run: make run_release_debug_test
